---
# tasks file for db
- name: Show info about the env this host belongs to, roles/app/tasks/main.yml
  debug:
    msg: "This host is in {{ env }} environment!!!"

- include: install_mongo.yml
- include: config_mongo.yml
